# Generated by Django 3.1.1 on 2020-09-17 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RecorteQueryConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offset', models.BigIntegerField(default=0)),
                ('limit', models.IntegerField(default=200000)),
            ],
            options={
                'verbose_name': 'Recorte Query Config',
                'verbose_name_plural': 'Recorte Query Config',
            },
        ),
    ]
