# Generated by Django 3.1.1 on 2020-09-17 19:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0002_recortequeryconfig_last_indexing_moment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recortequeryconfig',
            name='last_indexing_moment',
            field=models.DateTimeField(default=datetime.datetime(1970, 1, 1, 0, 0)),
        ),
    ]
