# Generated by Django 3.1.1 on 2020-09-17 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recorte',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_criacao', models.DateField(verbose_name='Data de Criação')),
                ('data_modificacao', models.DateTimeField(verbose_name='Data de Modificação')),
                ('numeracao_unica', models.CharField(max_length=20, verbose_name='Numeração Única')),
                ('recorte', models.TextField(verbose_name='Recorte')),
                ('data_publicacao', models.DateField(verbose_name='Data de Publicação')),
                ('codigo_diario', models.CharField(max_length=200, verbose_name='Código Diário')),
                ('caderno', models.CharField(max_length=200, verbose_name='Caderno')),
                ('novo_recorte', models.BooleanField(verbose_name='Novo Recorte')),
                ('paginas_diario', models.TextField(verbose_name='Páginas Diário')),
                ('nup_invalido', models.BooleanField(verbose_name='NUP Inválido')),
                ('nup_invalido_msg', models.CharField(max_length=120, verbose_name='NUP Invalido Mensagem')),
            ],
            options={
                'verbose_name': 'Recorte',
                'verbose_name_plural': 'Recortes',
                'ordering': ['id'],
                'managed': False,
            },
        ),
    ]
